//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanSil.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition_Runner
    {
        public int Id { get; set; }
        public int CompetitionId { get; set; }
        public int RunnerId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> Dorsal { get; set; }
        public byte[] ElapsedTime { get; set; }
        public Nullable<int> GeneralPosition { get; set; }
        public string GenderId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Elapsed_Time { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual Runner Runner { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
