//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanSil.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Runner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Runner()
        {
            this.Competition_Runner = new HashSet<Competition_Runner>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public string Email { get; set; }
        public Nullable<int> Telephone { get; set; }
        public Nullable<int> PostalCode { get; set; }
        public string GenderId { get; set; }
        public string DNI { get; set; }
        public string Club { get; set; }
        public Nullable<bool> IsLocalRunner { get; set; }
        public int YearBirthday { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition_Runner> Competition_Runner { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual DocumentType DocumentType { get; set; }
    }
}
